// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by siunit.rb; DO NOT EDIT.

package format

import "github.com/martinlindhe/unit"

// An example for each unit that can be handled by the SIUint function. This
// is used to test that all declared units in the unit package are handled.
var siUnitsHandled = map[string]interface{}{
	"Acceleration":          unit.Acceleration(1),
	"Angle":                 unit.Angle(1),
	"Area":                  unit.Area(1),
	"Datarate":              unit.Datarate(1),
	"Datasize":              unit.Datasize(1),
	"ElectricCurrent":       unit.ElectricCurrent(1),
	"Energy":                unit.Energy(1),
	"Force":                 unit.Force(1),
	"Frequency":             unit.Frequency(1),
	"Length":                unit.Length(1),
	"Mass":                  unit.Mass(1),
	"Power":                 unit.Power(1),
	"Pressure":              unit.Pressure(1),
	"Speed":                 unit.Speed(1),
	"Voltage":               unit.Voltage(1),
	"Volume":                unit.Volume(1),
	"AmountOfSubstance":     unit.AmountOfSubstance(1),
	"ElectricalConductance": unit.ElectricalConductance(1),
	"ElectricalResistance":  unit.ElectricalResistance(1),
	"Illuminance":           unit.Illuminance(1),
	"LuminousFlux":          unit.LuminousFlux(1),
	"LuminousIntensity":     unit.LuminousIntensity(1),
}
