// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by kwattrs.rb; DO NOT EDIT.

package pango

// StyleNormal sets the pango style to "normal".
func (n *Node) StyleNormal() *Node {
	return n.setAttr("style", "normal")
}

// Oblique sets the pango style to "oblique".
func (n *Node) Oblique() *Node {
	return n.setAttr("style", "oblique")
}

// Italic sets the pango style to "italic".
func (n *Node) Italic() *Node {
	return n.setAttr("style", "italic")
}
