// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by kwattrs.rb; DO NOT EDIT.

package pango

// UnderlineNone sets the pango underline to "none".
func (n *Node) UnderlineNone() *Node {
	return n.setAttr("underline", "none")
}

// UnderlineSingle sets the pango underline to "single".
func (n *Node) UnderlineSingle() *Node {
	return n.setAttr("underline", "single")
}

// UnderlineDouble sets the pango underline to "double".
func (n *Node) UnderlineDouble() *Node {
	return n.setAttr("underline", "double")
}

// UnderlineLow sets the pango underline to "low".
func (n *Node) UnderlineLow() *Node {
	return n.setAttr("underline", "low")
}

// UnderlineError sets the pango underline to "error".
func (n *Node) UnderlineError() *Node {
	return n.setAttr("underline", "error")
}
