// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by kwattrs.rb; DO NOT EDIT.

package pango

// UltraCondensed sets the pango stretch to "ultracondensed".
func (n *Node) UltraCondensed() *Node {
	return n.setAttr("stretch", "ultracondensed")
}

// ExtraCondensed sets the pango stretch to "extracondensed".
func (n *Node) ExtraCondensed() *Node {
	return n.setAttr("stretch", "extracondensed")
}

// Condensed sets the pango stretch to "condensed".
func (n *Node) Condensed() *Node {
	return n.setAttr("stretch", "condensed")
}

// SemiCondensed sets the pango stretch to "semicondensed".
func (n *Node) SemiCondensed() *Node {
	return n.setAttr("stretch", "semicondensed")
}

// StretchNormal sets the pango stretch to "normal".
func (n *Node) StretchNormal() *Node {
	return n.setAttr("stretch", "normal")
}

// SemiExpanded sets the pango stretch to "semiexpanded".
func (n *Node) SemiExpanded() *Node {
	return n.setAttr("stretch", "semiexpanded")
}

// Expanded sets the pango stretch to "expanded".
func (n *Node) Expanded() *Node {
	return n.setAttr("stretch", "expanded")
}

// ExtraExpanded sets the pango stretch to "extraexpanded".
func (n *Node) ExtraExpanded() *Node {
	return n.setAttr("stretch", "extraexpanded")
}

// UltraExpanded sets the pango stretch to "ultraexpanded".
func (n *Node) UltraExpanded() *Node {
	return n.setAttr("stretch", "ultraexpanded")
}
