// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by kwattrs.rb; DO NOT EDIT.

package pango

// XXSmall sets the pango size to "xx-small".
func (n *Node) XXSmall() *Node {
	return n.setAttr("size", "xx-small")
}

// XSmall sets the pango size to "x-small".
func (n *Node) XSmall() *Node {
	return n.setAttr("size", "x-small")
}

// Small sets the pango size to "small".
func (n *Node) Small() *Node {
	return n.setAttr("size", "small")
}

// Medium sets the pango size to "medium".
func (n *Node) Medium() *Node {
	return n.setAttr("size", "medium")
}

// Large sets the pango size to "large".
func (n *Node) Large() *Node {
	return n.setAttr("size", "large")
}

// XLarge sets the pango size to "x-large".
func (n *Node) XLarge() *Node {
	return n.setAttr("size", "x-large")
}

// XXLarge sets the pango size to "xx-large".
func (n *Node) XXLarge() *Node {
	return n.setAttr("size", "xx-large")
}
