// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by kwattrs.rb; DO NOT EDIT.

package pango

// UltraLight sets the pango weight to "ultralight".
func (n *Node) UltraLight() *Node {
	return n.setAttr("weight", "ultralight")
}

// Light sets the pango weight to "light".
func (n *Node) Light() *Node {
	return n.setAttr("weight", "light")
}

// WeightNormal sets the pango weight to "normal".
func (n *Node) WeightNormal() *Node {
	return n.setAttr("weight", "normal")
}

// Bold sets the pango weight to "bold".
func (n *Node) Bold() *Node {
	return n.setAttr("weight", "bold")
}

// UltraBold sets the pango weight to "ultrabold".
func (n *Node) UltraBold() *Node {
	return n.setAttr("weight", "ultrabold")
}

// Heavy sets the pango weight to "heavy".
func (n *Node) Heavy() *Node {
	return n.setAttr("weight", "heavy")
}
