# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'optparse'

attr_name = nil
OptionParser.new do |opts|
  opts.on('-n', '--name NAME', 'Attribute name') { |v| attr_name = v }
end.parse!
abort if attr_name.nil?

COPYRIGHT = File.readlines(__FILE__)
                .take_while { |line| line.start_with? '#' }
                .map { |comment| comment.sub('#', '//') }
                .join

out = File.open("kwattrs_#{attr_name}.go", 'w')
out.write(<<~HEADER)
  #{COPYRIGHT}
  // Code generated by kwattrs.rb; DO NOT EDIT.

  package pango
HEADER

ARGV.map { |it| it.split ':' }.each do |method_name, value|
  value = method_name.downcase if value.nil?
  out.write(<<~METHOD)

    // #{method_name} sets the pango #{attr_name} to "#{value}".
    func (n *Node) #{method_name}() *Node {
    \treturn n.setAttr("#{attr_name}", "#{value}")
    }
  METHOD
end
out.close
