# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require_relative 'run_cmd.rb'

COPYRIGHT = File.readlines(__FILE__)
                .take_while { |line| line.start_with? '#' }
                .map { |comment| comment.sub('#', '//') }
                .join

# Writes the standard copyright and generated file header, then provides a file
# handle for callers to append the actual go code, and finally runs the file
# through goimports to clean up any unused imports and format the code.
def write_go_file(name)
  out = File.open(name, 'w')
  out.puts COPYRIGHT
  out.puts
  out.puts "// Code generated by #{File.basename($PROGRAM_NAME)}; DO NOT EDIT."
  out.puts
  yield out
  out.close
  run_cmd('goimports', '-w', name)
end
